# Generated by Django 3.2.6 on 2021-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='아이디')),
                ('membername', models.CharField(max_length=64, verbose_name='사용자명')),
                ('memberpw', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록 일자')),
                ('gender', models.CharField(choices=[('M', '남성(Man'), ('W', '여성(Woman')], default='M', max_length=1, verbose_name='성별')),
                ('memberemail', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
            ],
        ),
    ]
