# Generated by Django 3.2.6 on 2021-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_memberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberprofile',
            field=models.TextField(default='자기소개를 작성해보세요^_^', max_length=100, null=True, verbose_name='자기소개'),
        ),
    ]
