# Generated by Django 3.2.6 on 2021-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lectureho',
            field=models.CharField(max_length=100, null=True, verbose_name='별명'),
        ),
    ]
