# Generated by Django 3.2.6 on 2021-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_lecture_lectureho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lectureName',
            field=models.CharField(max_length=64, unique=True, verbose_name='강의이름'),
        ),
    ]
