# Generated by Django 3.2.6 on 2021-09-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_lecture_lecturename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_lecture',
            name='lecture_id',
            field=models.ForeignKey(db_column='lectureid', on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='member.lecture'),
        ),
        migrations.AlterField(
            model_name='member_lecture',
            name='member_id',
            field=models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='member.member'),
        ),
    ]
