# Generated by Django 3.2.6 on 2021-09-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210910_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_lecture',
            old_name='lecture_id',
            new_name='lecture_idd',
        ),
        migrations.RenameField(
            model_name='member_lecture',
            old_name='member_id',
            new_name='member_idd',
        ),
    ]
