# Generated by Django 3.2.6 on 2021-09-10 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210910_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_lecture',
            name='lecture_idd',
        ),
        migrations.RemoveField(
            model_name='member_lecture',
            name='member_idd',
        ),
        migrations.AddField(
            model_name='member_lecture',
            name='lectureid',
            field=models.ForeignKey(db_column='lectureiddd',  on_delete=django.db.models.deletion.CASCADE, related_name='lectureidd', to='member.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_lecture',
            name='memberid',
            field=models.ForeignKey(db_column='memberiddd', on_delete=django.db.models.deletion.CASCADE, related_name='memberidd', to='member.member'),
            preserve_default=False,
        ),
    ]
