# Generated by Django 3.2.6 on 2021-09-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20210910_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_lecture',
            name='lectureid',
        ),
        migrations.RemoveField(
            model_name='member_lecture',
            name='memberid',
        ),
        migrations.AddField(
            model_name='member_lecture',
            name='lecture_id',
            field=models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='member.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member_lecture',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='member.member'),
            preserve_default=False,
        ),
    ]
