# Generated by Django 3.2.6 on 2021-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20210924_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_memo',
            field=models.TextField(default='강의 소개', max_length=1000, null=True, verbose_name='강의 소개'),
        ),
    ]
